/**
 * Sync the LitGUI panel's APP_VERSION constant with the integration manifest.
 *
 * Runs as `prebuild` (auto-runs before every `npm run build`) and as
 * `postinstall` (so freshly-cloned repos have src/version.js generated
 * before the IDE opens any file that imports it).
 *
 * Reads:  custom_components/volumio_ws/manifest.json
 * Writes: frontend/src/version.js
 *
 * Future: when the standalone plugin build is added (T45 Step 5), this
 * script will be extended or forked to read plugin/package.json instead.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const MANIFEST_PATH = resolve(
  __dirname,
  "../../custom_components/volumio_ws/manifest.json"
);
const OUTPUT_PATH = resolve(__dirname, "../src/version.js");

try {
  const manifest = JSON.parse(readFileSync(MANIFEST_PATH, "utf-8"));
  const version = manifest.version || "unknown";

  const content =
    `// Auto-generated by scripts/sync-version.js — do not edit.\n` +
    `// Source of truth: custom_components/volumio_ws/manifest.json\n` +
    `export const APP_VERSION = "${version}";\n`;

  writeFileSync(OUTPUT_PATH, content);
  console.log(`[sync-version] APP_VERSION = ${version}`);
} catch (err) {
  console.error("[sync-version] Failed:", err.message);
  process.exit(1);
}
